#!/bin/bash

project_dir=$(realpath .)
bin_dir=$project_dir/mage/bin
linux_dir=$project_dir/linux

sudo qemu-system-x86_64 -nographic -machine ubuntu \
	-enable-kvm -cpu host \
    -smp 6 -m 16G \
    -kernel $linux_dir/arch/x86_64/boot/bzImage \
    -drive file=$bin_dir/rootfs.ext3,if=none,id=disk0,format=raw -device virtio-blk-pci,drive=disk0 \
    -append "root=/dev/vda rw init=/bin/bash console=ttyS0"
